### PR TITLE
updated Vte 2.91

### PR DESCRIPTION
**Pull request by aissat**

### CODE REVIEW

**Comment by handicraftsman** [comment]
Cool, but why you commented icon?

**Comment by dveezhok** [comment]
Add screenshots, please.

**Comment by aissat** [comment]
because  
** (exec:18257): CRITICAL **: file /home/aye7/Project/vala_tuto/gtk-creator/main.vala: line 50: uncaught error: Failed to open file '/usr/share/icons/gtkcreator.png': No such file or directory (g-file-error-quark, 4)

**Comment by aissat** [comment]
screenshot from 2016-03-21 14-01-43

**Comment by handicraftsman** [comment]
I am going to upgrade it to new icons (and new design), when i'll finish required widget in vIdget library. Please, don't merge this pull request, because update will be large.

**Comment by handicraftsman** [comment]
@aissat, that error shows because of gtk-creator is not installed. In future, this icon will be built-in into G+C's source codes (yep, .vala files - it's possible)

**Comment by handicraftsman** [comment]
Please, don't delete this pull-request too

**Comment by aissat** [comment]
ok , i try aid you nd thnx for reply me .
about error  yes i konw whay .
and i redesign your project  and  redesign UI with Glade 
screenshot from 2016-03-22 11-53-01

**Pull request closed without merging**
